export const TIME_ZONES = [
	'America/New_York',
	'America/Chicago',
	'America/Denver',
	'America/Los_Angeles',
	'America/Anchorage',
	'America/Honolulu',
	'Europe/London',
	'Europe/Paris',
	'Europe/Berlin',
	'Europe/Moscow',
	'Asia/Tokyo',
	'Asia/Shanghai',
	'Asia/Singapore',
	'Asia/Dubai',
	'Asia/Kolkata',
	'Australia/Sydney',
	'Australia/Perth',
	'America/Sao_Paulo',
	'America/Buenos_Aires',
	'Africa/Cairo',
	'Africa/Johannesburg',
	'Pacific/Auckland',
	'UTC',
] as const;
