name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
          - uses: pnpm/action-setup@v4
            with:
              version: 9
          - uses: actions/setup-node@v3
            with:
                node-version: '20'

          - name: Install dependencies
            run: npm install

          - name: Lint
            run: npm run lint

          - name: Test
            run: npm run test

          - name: Build
            run: npm run build
