name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.0.0"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test

      - name: Build
        run: deno build
